# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Consumer Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false
env:
  PACT_BROKER_BASE_URL: https://chandramuddam.pactflow.io/
  PACT_BROKER_TOKEN: ctoBA7Cg_w5P-CDyIY94ZA

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set the value
      id: step_one
      run: |
        echo "GIT_COMMIT=$(`git rev-parse --short HEAD`+`date +%s`)" >> $GITHUB_ENV
        echo "GIT_BRANCH=$(`git rev-parse --abbrev-ref HEAD`)" >> $GITHUB_ENV
    - name: Set the value
      shell: bash
      run: |
       echo "GIT_COMMIT=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"
       echo "GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> "$GITHUB_ENV"
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./pact-consumer/PactConsumerTests/PactConsumerTests/PactConsumerTests.csproj
    - name: Build
      run: dotnet build --no-restore ./pact-consumer/PactConsumerTests/PactConsumerTests/PactConsumerTests.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal ./pact-consumer/PactConsumerTests/PactConsumerTests/PactConsumerTests.csproj
    - name: Download pact-cli
      run: curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v2.0.7/pact-2.0.7-linux-x86_64.tar.gz
    - name: extract pact-cli
      run: tar xzf pact-2.0.7-linux-x86_64.tar.gz
    - name: publish pact file
      run: ./pact/bin/pact-broker publish ./pact-consumer/PactConsumerTests/PactConsumerTests/bin/Debug/net6.0/pacts/Order-Consumer-Order-Provider.json --branch=${{env.GIT_BRANCH}} --consumer-app-version=${{env.GIT_COMMIT}} --broker-base-url=${{env.PACT_BROKER_BASE_URL}} --broker-token=${{env.PACT_BROKER_TOKEN}}
