# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PACT_BROKER_BASE_URL: https://chandramuddam.pactflow.io/
  PACT_BROKER_TOKEN: ctoBA7Cg_w5P-CDyIY94ZA
  GIT_COMMIT: ${{ github.sha }}
  GIT_REF: ${{ github.ref }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./pact-consumer/PactConsumerTests/PactConsumerTests/PactConsumerTests.csproj
    - name: Build
      run: dotnet build --no-restore ./pact-consumer/PactConsumerTests/PactConsumerTests/PactConsumerTests.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal ./pact-consumer/PactConsumerTests/PactConsumerTests/PactConsumerTests.csproj
    - name: Download pact-cli
      run: curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v2.0.7/pact-2.0.7-linux-x86_64.tar.gz
    - name: extract pact-cli
      run: tar xzf pact-2.0.7-linux-x86_64.tar.gz
    - name: publish pact file
      run: ./pact/bin/pact-broker publish ./pact-consumer/PactConsumerTests/PactConsumerTests/bin/Debug/net6.0/pacts/Order-Consumer-Order-Provider.json --consumer-app-version=1 --broker-base-url=${{env.PACT_BROKER_BASE_URL}} --broker-token=${{env.PACT_BROKER_TOKEN}}
